### ISSUE TITLE
Postfix helpers

### ISSUE THREAD

**Issue by bryantw111** [frapontillo/angular-bootstrap-duallistbox#10]
Hi! Thanks for creating this angular version of the duallistbox.

Can you explain how to access the helper1 and helper2 defined by the postfix? Is it a part of variable defined in ng-model?

I'm able to get the selected list from ng-model, but cannot find the removed list...

**Comment by frapontillo** [comment]
The first list will be named `PRE1` and the second one `PRE2`, where `PRE` is the string specified by `postfix` (defaults to `helper`).
