### ISSUE TITLE
doesnt update model variable

### ISSUE THREAD

**Issue by fatihpolatli** [frapontillo/angular-bootstrap-duallistbox#11]
hi,

i have an model variable `$scope.selectedData` in my controller. the problem is it doesnt update the real variable. i debugged directive and found that directive creates another variable inside its scope with same name and manipulate that, not the real one. besides, it see my variable inside 2 level upper parent.

thanks

**Comment by GBeans** [comment]
Something I've noticed is that it matters what order you specify the attributes.  My ngModel wasn't updating until I listed it first.

< select
    ng-model="selections"
    ng-options="el in elements"
    multiple
    bs-duallistbox
    >< /select >

**Comment by frapontillo** [comment]
I need a live demo (plnkr or jsfiddle).

**Comment by GBeans** [comment]
Well now that I've put the order back to the way you showed it, my model still updates and works.

**Comment by jpwits** [comment]
Hi, I have the same issue, even if I just use the example on GitHub, might be that I upgraded to Angular 1.4.8, Apparently if u do this 

$scope.selections = new Array(mySvc.things.length);

<select
 ngModel="selections[$index]"  ....

it works, I'll try

http://stackoverflow.com/questions/26180693/ngmodel-inside-ngrepeat-with-angular-bootstrap-duallistbox

**Comment by fatihpolatli** [comment]
It works better if you use object variable for ngmodel, i.e. [code]$scope.groups.selectedGroups[/code] intead of [code]$scope.selectedGroups[/code]

**Comment by jpwits** [comment]
I'm glad you are online, been struggling with this the whole day, ok that trick did not work either, the $Index one, what is strange is that I pass it with an array, that just contain the id's selected up front ...{[0], [1]...}, then it does show only these ones on the right LB, but if I add selections and I save it does not update the array?

**Comment by jpwits** [comment]
Ok, I found out what is the problem...I used it in a tabset....apparently this is known...check out: http://stackoverflow.com/questions/27513462/angularjs-ngmodel-doesnt-work-inside-a-ui-bootstrap-tabset

Still trying to figure it out, since I have many other components that I use inside the tabset and they all are updating

**Comment by jpwits** [comment]
Ok...I added this to my controller :  $scope.data = {} and then changed my select to ....  <select ng-model="data.model" ... then it works, not 100% sure why, but it does...probably have to read all about primitive scopes, etc.
