### ISSUE TITLE
How to set initial selected items?

### ISSUE THREAD

**Issue by GBeans** [frapontillo/angular-bootstrap-duallistbox#18]
First I'd like to say thank you for writing a quality wrapper for the Bootstrap Dual Listbox.  One thing I'm not able to figure out is how to set the initially selected values for the listbox.  Here's how I have it declared:
`<select ng-options="p.labelField for p in param.ValidValues track by p.valueField"
                multiple="multiple"
                ng-model="param.values"
                json = "false"
                bs-duallistbox
                ng-change="param.onChange(param)"
                name="{{param.Name}}"
                class="form-control"
                required></select>`

I tried populating the param.values with the initially selected items but it doesn't take.  Everything works as expected when I go to read the selected items after the user selects them.
I have also tried modifying my param.ValidValues by adding "param.selected = true".
Any suggestions?

**Comment by GBeans** [comment]
Figured out what I needed to do.  The param.values needs to be populated with a list of the actual objects contained in my param.ValidValues.  This is based on the fact that ng-model for a select compares by reference, not value.

**Comment by dstep2007** [comment]
@GBeans how did you get the actual values in to param.Values from param.ValidValues?  Can you post some sample code?  I am having the same issue with trying to get initially selected values to show.  Thank you

**Comment by dstep2007** [comment]
Nevermind, figured it out.  For anyone else who might be wondering:

In your HTML:
```
<select
                            ng-options="c.name for c in main.countries"
                            multiple
                            ng-model="main.selected"
                            bs-duallistbox
                            ></select>
```

in your controller:
```
this.countries = [
        { name: 'Amsterdam' },
        { name: 'Washington' },
        { name: 'Sydney' },
        { name: 'Cairo' },
        { name: 'Beijing' }];

    this.selected = [
        this.countries[0],
        this.countries[1]];
```
