### ISSUE TITLE
Know when the NonSelected list box is empty

### ISSUE THREAD

**Issue by jmorrisIII** [frapontillo/angular-bootstrap-duallistbox#19]
Is there a way to know when the NonSelected list box is empty? I did a $scope.$watch to know when a filter is being applied but I need to know what is left in the list afterwards. More specifically when the list is empty. 

```
        $scope.$watch(
            "vm.settings.filterNonSelected",
            function handleFooChange( newValue, oldValue ) {
                console.log( "vm.fooCount:", newValue );
            }
        );
```

**Comment by frapontillo** [comment]
You need to use the `ng-model` to do that, and you can evaluate if there's anything selected by checking the array size.

**Comment by jmorrisIII** [comment]
I am probably doing something wrong.[The](https://drive.google.com/open?id=0B7qRPBu8FCiaX3ZRaWJPeFpRSTQ) list on the left is the one I need to know when it is empty.Basically if the item I am filtering for is not in the list. The ng-model contains the list of selected items on the right.

**Comment by frapontillo** [comment]
I'm sorry but I can't reply via personal email. Please open an issue on the
repo.

Best,

On Fri, Jun 24, 2016 at 1:51 PM jmorrisIII <notifications@github.com> wrote:

> I am probably doing something wrong.The
> <https://drive.google.com/open?id=0B7qRPBu8FCiaX3ZRaWJPeFpRSTQ> list on
> the left is the one I need to know when it is empty.Basically if the item I
> am filtering for is not in the list. The ng-model contains the list of
> selected items on the right.
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/frapontillo/angular-bootstrap-duallistbox/issues/19#issuecomment-228337370>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABFmDozvqg07vE2ebixCkfX6QI8mpWnQks5qO9LSgaJpZM4IeA9o>
> .
>
-- 
Francesco Pontillo

**Comment by jmorrisIII** [comment]
Open up a new issue? Not sure what the previous comment meant about personal email.

**Comment by frapontillo** [comment]
I need to look at a live plunker to help you.

Sorry for the previous email, too.
