### ISSUE TITLE
element.bootstrapDualListbox is not a function

### ISSUE THREAD

**Issue by achands** [frapontillo/angular-bootstrap-duallistbox#2]
I am getting an error when I tried using it

TypeError: element.bootstrapDualListbox is not a function.

My bower.json looks like below

{
  "name": "****_",
  "version": "0.0.1",
  "description": "**_****",
  "dependencies": {
    "bootstrap": "~3",
    "angular": "~1.2",
    "angular-resource": "~1.2",
    "angular-animate": "~1.2",
    "angular-mocks": "~1.2",
    "angular-bootstrap": "~0.11.0",
    "angular-ui-utils": "~0.1.1",
    "angular-ui-router": "~0.2.10",
    "angular-strap": "~2.0.5",
    "angular-file-upload": "~1.1.1",
    "angularjs-dropdown-multiselect": "~1.5.2",
    "ng-grid": "~2.0.13",
    "ng-currency": "~0.7.6",
    "angular-camera": "~0.1.3",
    "pdfmake": "~0.1.8",
    "ng-pdfviewer": "~0.2.1",
    "angular-bootstrap-duallistbox": "~0.0.2"
  }
}

**Comment by luisestebanas** [comment]
I have this error:

```
TypeError: element.bootstrapDualListbox is not a function
    at init (bsDuallistbox.js:173)
    at initMaybe (bsDuallistbox.js:159)
    at bsDuallistbox.js:117
    at Scope.$digest (angular.js:16664)
    at Scope.$apply (angular.js:16928)
    at done (angular.js:11266)
    at completeRequest (angular.js:11464)
    at XMLHttpRequest.requestLoaded (angular.js:11405)
```

I added all bootstrap-duallistbox dependencies and the angular-bootstrap-duallistbox/dist/angular-bootstrap-duallistbox.js in the index.html and does not work. can you help me? thanks

**Comment by xolisan** [comment]
Hi Luis, 

Please make sure if you import the Jquery dependency before angular.js.

Best regards,
Sandro

**Comment by luisestebanas** [comment]
Thank you Sandro. you're right, that was my error.

**Comment by slimshadddyyy** [comment]
After jQuery is loaded, then AngularJs, included below



```
    <script src="assets/js/lib/Angular/angular-duallistbox/angular-bootstrap-duallistbox.js"></script>
    <script src="common/directives/bsDuallistbox/bsDuallistbox.js"></script>
```



```

This in angular.module
`'frapontillo.bootstrap-duallistbox'`

Error: element.bootstrapDualListbox is not a function.

What am I missing here ?
```

**Comment by frapontillo** [comment]
The right order is jquery, dual list box and only in the end the directive.

**Comment by slimshadddyyy** [comment]
is not the above same ?

```
 <script src="assets/plugins/jQuery/jQuery-2.1.4.min.js"></script>
<script src="assets/js/lib/Angular/1.5.5/angular.js"></script>
<script src="assets/js/lib/Angular/angular-duallistbox/angular-bootstrap-duallistbox.js"></script>
        <script src="common/directives/bsDuallistbox/bsDuallistbox.js"></script>
```

??

**Comment by frapontillo** [comment]
No, you're putting the directive before the original dual list box

**Comment by slimshadddyyy** [comment]
`angular-bootstrap-duallistbox/src/directives/bsDuallistbox.js is my common/directives/bsDuallistbox/bsDuallistbox.js file `
AND
```
angular-bootstrap-duallistbox/dist/angular-bootstrap-duallistbox.js is my
assets/js/lib/Angular/angular-duallistbox/angular-bootstrap-duallistbox.js
```

**Comment by slimshadddyyy** [comment]
Is the below order now correct ?

<link rel="stylesheet" href="assets/css/dist/css/bootstrap-duallistbox.min.css">
<script src="assets/plugins/jQuery/jQuery-2.1.4.min.js"></script>
<script src="assets/css/dist/js/jquery.bootstrap-duallistbox.min.js"></script>
<script src="assets/js/lib/Angular/1.5.5/angular.js"></script>
<script src="assets/js/lib/Angular/angular-duallistbox/angular-bootstrap-duallistbox.min.js"></script>
<script src="common/directives/bsDuallistbox/bsDuallistbox.js"></script>

if yes, I am getting below output
![untitled](https://cloud.githubusercontent.com/assets/19320421/16006102/d6b2c550-3188-11e6-933a-853c0a000da9.png)

**Comment by frapontillo** [comment]
Why are you including `common/directives/bsDuallistbox/bsDuallistbox.js`? You only need to include the full library under `dist` once.

**Comment by slimshadddyyy** [comment]
I omitted it. Please check my question here - http://stackoverflow.com/questions/37788872/angular-js-implement-duallistbox

I am still facing the same issue. I know I am close but can not get it working. Need your help to overcome this issue.

Thanks
