### ISSUE TITLE
How to keep single/multiple option values selected ?

### ISSUE THREAD

**Issue by slimshadddyyy** [frapontillo/angular-bootstrap-duallistbox#20]
I have successfully integrated duallistbox with dynamic data. The data is saved but at the time of edit, I need to show the options saved in db as selected. 
For ex: While saving user data, we are showing user group in duallistbox and based on options selected, the data is being saved. At the time of edit, how do I show the option(s) as selected ?

P.S. The options will be dynamically passed from web-service call

Below image shows what I am trying to achieve. I could not find API for the same. Please guide

![untitled](https://cloud.githubusercontent.com/assets/19320421/16042607/3a1d4cd4-3259-11e6-8eda-067647c7152b.png)

Thanks.

**Comment by frapontillo** [comment]
If you follow the example you can understand how to do it.
Your `ng-model` should be set to an array that contains the tracking properties for the array bound in `ng-options`.

``` html
<select
    ng-model="model"
    ng-options="obj as obj.text for obj in list track by obj.id"
...
```

**Comment by slimshadddyyy** [comment]
Sir, I am using the array to track properties, but unsure on following items
1) How to select specific object data viz, id or text ?
2) How to keep that specific option selected ?

```
<select
              ng-model="model"
              ng-options="obj as obj.text for obj in list track by obj.id"
              multiple
...
<h3>You have selected: {{model}}</h3> 

Shows You have selected: [{"id":"_1","text":"one"}], but not id or text.
```

**Comment by frapontillo** [comment]
Sorry, I forgot how the inner parts work, haven't worked on this for a while.

The first part tells you what's going into the model, in this case the whole `obj`, if you only want the IDs in the model, then use `ng-options="obj.id as obj.text for obj in list track by obj.id"`

**Comment by slimshadddyyy** [comment]
Okay, i can see `obj.id` selected, but not the options which are clicked do not move to right side.

See the image below

![untitled](https://cloud.githubusercontent.com/assets/19320421/16043408/28556bb8-325d-11e6-8d8a-bf03872d9c53.png)

**Comment by frapontillo** [comment]
I need a live demo to help you with that. You can use plunker.

**Comment by slimshadddyyy** [comment]
here you go sir - http://plnkr.co/edit/gjGqAfXImH8tIW2stERj?p=preview

**Comment by frapontillo** [comment]
As I already told you, you do not have to put my directive twice. Just use the file in the dist folder, do not put the module again.

**Comment by slimshadddyyy** [comment]
Sir, pls let me know where I have put your directive twice and which file I am suppose to remove ? I have changed setting of plunker. You can now edit.

**Comment by frapontillo** [comment]
This is the proper way to do it: http://plnkr.co/edit/Yk49QLBZXGuT0ntASM4i?p=preview
Apparently you can't use the `obj.id` notation, the model will contain the whole object, but it works.

**Comment by slimshadddyyy** [comment]
Yes the model does contain the whole object. But then my question remains the same. On saving the form, how can I fetch selected (post) data and on editing the page, how can I make the options selected as asked above ?

**Comment by frapontillo** [comment]
You need to set your model yourself right after loading the list.

**Comment by slimshadddyyy** [comment]
I was able to achieve the above using `ng-options="ugrp.id as ugrp.username for ugrp in userGroup"` but how can I show already selected option values in _`helper2` i.e. right side on page load ? Then user can again select few more from left side and then save it ?

Plunker - http://plnkr.co/edit/Yk49QLBZXGuT0ntASM4i?p=preview

**Comment by frapontillo** [comment]
You **can't** use `ugrp.id`, you need to use `ugrp`, please see my latest plunker I linked you. Did you open it?

**Comment by slimshadddyyy** [comment]
Sir, your plunker works well, but I need to fetch the id's for user group when form is submitted. So in my plunker it gives only id of usergroup like below

`{"username":"911","firstname":"John","lastname":"P","email":"vv@rr.com","usergroup":["1","3"]}`

But question is how to show that id 1,3 on right side i.e.

`<select multiple="multiple" id="bootstrap-duallistbox-selected-list_" class="form-control" name="_helper2" style="height: 162px;"><option label="John" value="string:1" data-sortindex="0">John</option><option label="Doe" value="string:3" data-sortindex="1">Doe</option></select>`

**Comment by frapontillo** [comment]
As I have already told you

> You need to set your model yourself right after loading the list.

http://plnkr.co/edit/kJj2WB?p=preview

**Comment by slimshadddyyy** [comment]
How about showing more than one field selected on right side. Below code does not work.

```
 // THIS PRELOADS YOUR MODEL
    $scope.model = [{
        'id': '_1,_2',
        'text': 'one'
      }];
```

Or is there any other convention to use for multiple records ?

**Comment by slimshadddyyy** [comment]
Hi frapontillo,

if you could please respond to my above question, would be helpful,

Thanks.
