### ISSUE TITLE
Large number of records and performance.

### ISSUE THREAD

**Issue by jmorrisIII** [frapontillo/angular-bootstrap-duallistbox#21]
We have about 12,000 records we would like to display and filter. Not sure what the most efficient way is to do this. When I bind to them it basically kills the page.

```
ng-options="obj.fullNameEmail for obj in vm.formattedGmContacts track by obj._id"
```

**Comment by frapontillo** [comment]
This directive isn't adequate to support that many elements, nor you should load them all at once in your page with any directive really.
