### ISSUE TITLE
Tooltip on items

### ISSUE THREAD

**Issue by martinobordin** [frapontillo/angular-bootstrap-duallistbox#28]
Is it possible to show a tooltip when hovering on a single item?
This because I have very long text per each item and I cannot see it entirely:

![image](https://user-images.githubusercontent.com/1763288/32915817-76627d4e-cb1a-11e7-8764-31b498b7dcbe.png)

**Comment by mksp2016** [comment]
facing the same issue .. +1

**Comment by martinobordin** [comment]
@frapontillo Do you think it is possible?

**Comment by martinobordin** [comment]
@mksp2016 I solved adding a line of code inside **jquery.bootstrap-duallistbox.js** (_base library, not angular wrapper_)

Open the file, find the function **refreshSelects** and after the line     
`var $item = $(item);` 
just add  
`$(item).prop("title", $(item).text());`
 
So this should be the complete function:
```
function refreshSelects(dualListbox) {
	dualListbox.selectedElements = 0;

	dualListbox.elements.select1.empty();
	dualListbox.elements.select2.empty();

	dualListbox.element.find('option').each(function (index, item) {
	  var $item = $(item);

	  $(item).prop("title", $(item).text());

		if ($item.prop('selected')) {
			dualListbox.selectedElements++;
			dualListbox.elements.select2.append($item.clone(true).prop('selected', $item.data('_selected')));
		} else {
			dualListbox.elements.select1.append($item.clone(true).prop('selected', $item.data('_selected')));
		}
	});

	if (dualListbox.settings.showFilterInputs) {
		filter(dualListbox, 1);
		filter(dualListbox, 2);
	}
	refreshInfo(dualListbox);
}
```
