### ISSUE TITLE
Cannot make it work with your example on JSFiddle

### ISSUE THREAD

**Issue by rtp-calpoly** [frapontillo/angular-bootstrap-duallistbox#5]
I have created the following JSFiddle with your example, but I cannot make it work:

    http://jsfiddle.net/rtubio/u3rLhqxa/2/

I am always getting the following error on the JavaScript console:

    Error: d.bootstrapDualListbox is not a function
        .link/m/</<@https://raw.githubusercontent.com/frapontillo/angular-bootstrap-duallistbox/master/dist/angular-bootstrap-duallistbox.min.js:9:1994
    $CompileProvider/this.$get</Attributes.prototype.$set/<@http://cdnjs.cloudflare.com/ajax/libs/angular.js/1.2.1/angular.js:5333:13
    ... etc...

Any ideas?

**Comment by frapontillo** [comment]
You can't use GitHub as a CDN, that's the issue:

```
Refused to execute script from 'https://raw.githubusercontent.com/frapontillo/angular-bootstrap-duallistbox/master/dist/angular-bootstrap-duallistbox.min.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.
```
