### ISSUE TITLE
Cannot populate the list of selected items from the controller

### ISSUE THREAD

**Issue by HansFritz** [frapontillo/angular-bootstrap-duallistbox#7]
I am trying something like this in my controller:

```javascript
GroupsService.getAllUsersByGroup.query({id: idToEdit}).$promise.then(function (resp) {
                $scope.selectedUsers = resp;
                //selectedUsers is populated, but the list is not refreshed
                console.log(resp);
                groupDataLoaded = true;
});
```

And in my view I have this:

```html
<select ng-model="selectedUsers" ng-options="u as u.username for u in users" multiple bs-duallistbox move-on-select="false">
</select>
```

I need to display the already selected users in the right list and the rest of the users in the left one when my page loads (sort of an update group feature). My problem is: I can select users from the list on the left, but not from the controller. Two way binding just doesn't seem to work for me.

No idea if this is a bug or not an included feature.

**Comment by frapontillo** [comment]
Can you please add a plnkr?

**Comment by blarsen06** [comment]
I'm having the same issue as HansFritz.  When loading the available items, and the already selected items (same format of multi-select data in both lists), only the available items appear.  It seems like the ng-model isn't binding to the collection.  If you've got code to bind  / or watch, I'll take a look in your directive (or wire one up).  The Plnkr thing is difficult, because I'm working with live data ... I suspect that's why you didn't hear back from HansFritz as well.

**Comment by frapontillo** [comment]
You can simulate live data with hardcoded ones.

**Comment by blarsen06** [comment]
Here ya go.  Can you tell me what looks wrong (aside from the button styles of course).  http://plnkr.co:80/kEOFaj3A22YCw6BmXxMi

**Comment by frapontillo** [comment]
Confirmed bug.
http://plnkr.co/edit/iyi08XKqc5Lvhycf6tDU?p=preview

**Comment by jean-merelis** [comment]
You have to use **"track by"** instead **"as"** in ng-options

Instead this: 
```html
 <select ng-model="selected" ng-options="av as av.name for av in available" multiple bs-duallistbox></select>
```

Uses:
```html
 <select ng-model="selected" ng-options="av.name for av in available track by av.id" multiple bs-duallistbox></select>
```

**Comment by tysonnero** [comment]
I am having the same issue
@jean-merelis Your solution worked for me
